% as the sources are all on data with interpolated channels (with no info on ICA)
% I will calculate the head model, noise covariance (identity matrix) and
% inversion kernel, only once for a subject that will act as "reference".

% Input files
ref_file = {'sub-032301/sub-032301_EC/data_block001_bl_interpbad.mat'};

% Start a new report
bst_report('Start', ref_file);

HM = bst_process('CallProcess', 'process_headmodel', ref_file, [], ...
    'Comment',     '', ...
    'sourcespace', 1, ...  % Cortex surface
    'meg',         1, ...  % 
    'eeg',         2, ...  % 3-shell sphere
    'ecog',        1, ...  % 
    'seeg',        1);  % 


NoiseCov = bst_process('CallProcess', 'process_noisecov', ref_file, [], ...
    'baseline',       [,], ...
    'datatimewindow', [,], ...
    'sensortypes',    'MEG', ...
    'target',         1, ...  % Noise covariance     (covariance over baseline time window)
    'dcoffset',       1, ...  % Block by block, to avoid effects of slow shifts in data
    'identity',       1, ...
    'copycond',       0, ...
    'copysubj',       0, ...
    'copymatch',      1, ...
    'replacefile',    1);  % Replace

% Process: Compute sources [2018]
Sources = bst_process('CallProcess', 'process_inverse_2018', ref_file, [], ...
    'output',  1, ...  % Kernel only: shared
    'inverse', struct(...
         'Comment',        'sLORETA: EEG', ...
         'InverseMethod',  'minnorm', ...
         'InverseMeasure', 'sloreta', ...
         'SourceOrient',   {{'free'}}, ...
         'Loose',          0.2, ...
         'UseDepth',       0, ...
         'WeightExp',      0.5, ...
         'WeightLimit',    10, ...
         'NoiseMethod',    'reg', ...
         'NoiseReg',       0.1, ...
         'SnrMethod',      'fixed', ...
         'SnrRms',         1e-06, ...
         'SnrFixed',       3, ...
         'ComputeKernel',  1, ...
         'DataTypes',      {{'EEG'}}));

% Save and display report
ReportFile = bst_report('Save', Sources);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);

