% Script generated by Brainstorm (24-Sep-2020)
% this script copy the source kernels, head model and noise covariance (which is identity matrix) to all subjects and conditions


% clear
cd('/mnt/raid/RU1/software/brainstorm3/')
brainstorm %server

addpath(genpath('/mnt/raid/RU1/Analysis_scripts_code/LEMON_analyses/functions/'));

ProtocolName = 'LEMON_ver1';
iProtocol = bst_get('Protocol', ProtocolName);
gui_brainstorm('SetCurrentProtocol', iProtocol);


my_subjects = bst_get('ProtocolSubjects');
Subj_names = {my_subjects.Subject.Name};
Subj_names = setdiff(Subj_names, {'Group_analysis', 'Digitize'}); % exclude Group_analysis

condition_names = {'_EC', '_EO'};

% hard-coded
ref_files_path = '/mnt/raid/RU1/BrainstormDB_new/LEMON_ver1/data/sub-032301/sub-032301_EC/'
ref_filenames = {'headmodel_surf_eeg_3sphereberg.mat',...
    'noisecov_full.mat',...
    'results_sLORETA_EEG_KERNEL_220113_1507.mat'};


protocol_data_path = '/mnt/raid/RU1/BrainstormDB_new/LEMON_ver1/data/';


for iSubj = 1:length(Subj_names)
    
    curr_subj = Subj_names{iSubj};
    
    for iCond = 1:length(condition_names)
        
        curr_cond = condition_names{iCond};
        
        % skip the ref file
        if ~(strcmp(curr_subj,'sub-032301') & strcmp(curr_cond,'_EC'))
            curr_subj_dir = dir([protocol_data_path, curr_subj]);
            curr_subj_dir_name = {curr_subj_dir.name};
            curr_cond_dir = sel_files_bst(curr_subj_dir_name, curr_cond, '@');
            
            curr_path = [protocol_data_path, curr_subj, '/', curr_cond_dir{1}, '/'];
            
            for iFile = 1:length(ref_filenames)
                copyfile([ref_files_path, ref_filenames{iFile}], [curr_path, ref_filenames{iFile}]);
            end;
            
        end
    end;
end
